version: 8.2

preset: laravel

disabled:
  - laravel_braces
  - laravel_phpdoc_alignment
  - laravel_phpdoc_separation
  - normalize_nullable_type_declaration
  - control_structure_continuation_position
