preset: laravel

enabled:
  - align_multiline_comment
  - class_attributes_separation
  - class_definition
  - control_structure_continuation_position
  - nullable_type_declaration
  - ordered_types
  - phpdoc_separation
  - phpdoc_types_order

disabled:
  - no_superfluous_phpdoc_tags
