version: 8.2

preset: laravel

disabled:
  - braces
  - concat_without_spaces
  - laravel_braces
  - laravel_phpdoc_alignment
  - laravel_phpdoc_separation
  - normalize_nullable_type_declaration
  - no_unneeded_braces
  - no_unneeded_control_parentheses
