preset: laravel

enabled:
  - align_multiline_comment
  - class_attributes_separation
  - class_definition
  - control_structure_continuation_position
  - nullable_type_declaration
  - ordered_types
  - phpdoc_separation
  - phpdoc_types_order

disabled:
  - no_superfluous_phpdoc_tags

rules:
  align_multiline_comment:
    comment_type: phpdocs_like

  class_attributes_separation:
    elements:
      const: only_if_meta
      method: one
      property: only_if_meta
      trait_import: none

  class_definition:
    multi_line_extends_each_single_line: false

  control_structure_continuation_position:
    position: next_line

  nullable_type_declaration:
    syntax: union

  ordered_types:
    null_adjustment: always_last

  phpdoc_separation:
    groups:
      - [ deprecated, link, see, since ]
      - [ author, copyright, license ]
      - [ category, package, subpackage ]
      - [ property, property-read, property-write ]
      - [ param ]
      - [ return, throws ]

  phpdoc_types_order:
    null_adjustment: always_last
